services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped

  apilog:
    image: bigdatawirtz/apilog:latest
    container_name: apilog
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017/
